# Generated by Django 4.2.1 on 2023-11-06 06:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CMS_billing', '0001_initial'),
        ('CMS_HC_application', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('addpatients_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('addpatients_linel', models.CharField(max_length=50)),
                ('addpatients_line2', models.CharField(max_length=59)),
                ('landmark', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=38)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('bank_details_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('pancard_number', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('insurance_code', models.CharField(max_length=255)),
                ('patient_first_name', models.CharField(max_length=255)),
                ('patient_last_name', models.CharField(max_length=255)),
                ('patient_middle_name', models.CharField(blank=True, max_length=255)),
                ('patient_code', models.CharField(max_length=20)),
                ('patient_prefix', models.CharField(blank=True, max_length=255)),
                ('patient_suffix', models.CharField(blank=True, max_length=255)),
                ('patient_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=255)),
                ('patient_age_years', models.PositiveSmallIntegerField()),
                ('patient_age_months', models.PositiveSmallIntegerField()),
                ('patient_age_days', models.PositiveSmallIntegerField()),
                ('patient_isprimary', models.BooleanField(default=False)),
                ('patient_isrider', models.BooleanField(default=False)),
                ('patient_occupation', models.CharField(max_length=255)),
                ('service_provider_name', models.CharField(max_length=255)),
                ('service_provider_code', models.CharField(max_length=255)),
                ('admitted_reason', models.TextField(max_length=255)),
                ('disease_start_date', models.DateField()),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('police_reported', models.BooleanField(default=False)),
                ('fir_attached', models.BooleanField(default=False)),
                ('pre_hospital_period', models.DurationField()),
                ('post_hospital_period', models.DurationField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_qualification', models.CharField(max_length=255)),
                ('doctor_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('type_of_admission', models.CharField(max_length=255)),
                ('total_claim_amount', models.FloatField()),
                ('discharge_status', models.CharField(choices=[('Cured', 'Cured'), ('Improved', 'Improved'), ('Unchanged', 'Unchanged'), ('Dead', 'Dead')], max_length=255)),
                ('abuse_injury', models.BooleanField(default=False)),
                ('alcohol_injury', models.BooleanField(default=False)),
                ('abuse_report', models.FileField(blank=True, upload_to='abuse_reports/')),
                ('alcohol_report', models.FileField(blank=True, upload_to='alcohol_reports/')),
                ('claim_place', models.CharField(max_length=255)),
                ('claim_date', models.DateField()),
                ('claim_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=255)),
                ('claim_number', models.CharField(max_length=255, unique=True)),
                ('claim_PDF', models.FileField(blank=True, upload_to='claim_pdfs/')),
                ('bank_details', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CMS_patient_registration.bankdetails')),
                ('contact_details', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CMS_HC_application.contactdetails')),
                ('insurance_payer_details', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CMS_billing.insurancepayerdetails')),
                ('patients_add_details', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CMS_patient_registration.addressdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('personal_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('claim_status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('denied', 'denied')], default='pending', max_length=20)),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('patient_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_name_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_weight', models.FloatField()),
                ('patient_height', models.PositiveIntegerField()),
                ('patient_image', models.ImageField(blank=True, null=True, upload_to='patient/')),
                ('patient_marital_status', models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried'), ('divorced', 'divorced'), ('widow', 'widow')], default='unmarried', max_length=20)),
                ('patient_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('trans', 'trans')], max_length=10)),
                ('patient_is_handicap', models.BooleanField(default=False)),
                ('patient_date_of_birth', models.DateField()),
                ('patient_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_aadhar_card_number', models.CharField(max_length=16)),
                ('patient_aadhar_card_image', models.ImageField(blank=True, null=True, upload_to='patient_aadhar/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('contact_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS_HC_application.contactdetails')),
                ('patients_add_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS_patient_registration.addressdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('claim_document_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('claim_name', models.CharField(max_length=20)),
                ('claim_code', models.CharField(max_length=20)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_documents', to='CMS_patient_registration.claim')),
            ],
        ),
    ]
