# Generated by Django 4.2.4 on 2023-11-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CMS_patient_registration', '0001_initial'),
        ('CMS_patient_sheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='room_category',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_category_patient', to='CMS_patient_sheduling.roomcategory'),
        ),
    ]
