# Generated by Django 4.2.1 on 2023-11-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_patient_registration', '0003_remove_claim_patient_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='room_category',
        ),
    ]
