# Generated by Django 4.2.1 on 2023-11-06 06:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason_of_appointment', models.TextField()),
                ('appointment_for', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('contact_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('alternate_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('email_identifier', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternate_email_identifier', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
