# Generated by Django 4.2.1 on 2023-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_HC_application', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='a_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
