# Generated by Django 4.2.1 on 2023-11-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_HC_application', '0005_contactdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='user',
        ),
    ]
