# Generated by Django 4.2.4 on 2023-11-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
