# Generated by Django 4.2.1 on 2023-11-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_auth', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service_provider',
        ),
    ]
