# Generated by Django 4.2.7 on 2023-11-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_auth', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Nurse', 'Nurse'), ('Wardboy', 'Wardboy')], max_length=20),
        ),
    ]
